export {
  type ActiveHill,
  endHillNow,
  HILL_LOST_LINE,
  HILL_READOUT_NONE_LINE,
  HILL_TAKEN_LINE,
  HILL_VAULT_LINE,
  type HillPhase,
  type HillState,
  type HillVaultCredit,
  hillFallenLine,
  hillInfoFor,
  hillPlanFor,
  hillRankLine,
  hillReadoutLine,
  hillRiseLine,
  hillStillStandsLine,
  hillWarningLine,
  NO_HILL_VAULT_CREDIT,
  newHillState,
  pickHillSpot,
  riseHillNow,
  spawnHill,
  spawnHillNow,
  updateHill,
  warnNextHillNow,
} from './hill';
export {
  HILL_BOUNTY_BASE_HONOR,
  HILL_BOUNTY_DEATH_STREAK_HONOR,
  HILL_BOUNTY_KILL_STREAK_HONOR,
  HILL_BOUNTY_REPEAT_CAP,
  HILL_CALLOUT_SECONDS,
  HILL_SHUTDOWN_STREAK,
  type HillCalloutKind,
  type HillStreakCalloutKind,
  hillBountyHonor,
  hillRepeatHonorMultiplier,
  hillStreakCallout,
} from './hill_bounty_rules';
export {
  HILL_RANKING_SHOWN,
  type HillHoldRecord,
  hillLongestHolds,
  hillRanking,
  hillVaultPayees,
} from './hill_ranking';
export {
  HILL_ACCRUAL_SECONDS,
  HILL_CAPTURE_SECONDS,
  HILL_DURATION_SECONDS,
  HILL_FIRST_WINDOW_AT_SECONDS,
  HILL_LATEST_WARN_OFFSET_SECONDS,
  HILL_NOTICE_SECONDS,
  HILL_RADIUS,
  HILL_RAMP_MAX_HONOR,
  HILL_RAMP_STEP_HONOR,
  HILL_RAMP_STEP_SECONDS,
  HILL_VAULT_MIN_HOLD_SECONDS,
  HILL_VAULT_MIN_INSIDE_SECONDS,
  HILL_WARNING_SECONDS,
  HILL_WINDOW_SECONDS,
  type HillSpotProbe,
  type HillStanding,
  type HillTimes,
  hillChallengeStands,
  hillContains,
  hillContestStep,
  hillGroupKey,
  hillHonorPerPayout,
  hillLeader,
  hillMinutesUntil,
  hillSpotIsOpen,
  hillStanding,
  hillTimes,
  hillTimesFrom,
  hillWindowAt,
} from './hill_rules';
export {
  ARENA_DAILY_TAPER_FLOOR_START,
  ARENA_DAILY_TAPER_START,
  ARENA_LOSS_HONOR_SHARE,
  ARENA_REPEAT_DR,
  arenaRepeatHonorMultiplier,
  awardBattlegroundAssistHonor,
  awardBattlegroundHonor,
  awardBattlegroundKillHonor,
  awardFiestaCompletionHonor,
  awardFiestaKillHonor,
  awardRankedArenaResultHonor,
  BATTLEGROUND_ASSIST_HONOR,
  BATTLEGROUND_FIRST_WIN_BONUS_HONOR,
  BATTLEGROUND_KILL_HONOR,
  BATTLEGROUND_LOSS_HONOR,
  BATTLEGROUND_RESULT_DR,
  BATTLEGROUND_WIN_HONOR,
  type BattlegroundHonorAward,
  battlegroundResultMultiplier,
  bgFirstWinBonusAvailable,
  FIESTA_COMPLETION_HONOR,
  FIESTA_KILL_HONOR,
  FIESTA_WIN_BONUS_HONOR,
  grantHonor,
  HONOR_REPEAT_DR,
  honorTeamIdentity,
  normalizeHonorCounter,
  normalizeHonorDailyState,
  RANKED_ARENA_LOSS_HONOR,
  RANKED_ARENA_WIN_HONOR,
  repeatHonorMultiplier,
} from './honor';
export {
  DOUBLE_HONOR_LEAD_HOURS,
  DOUBLE_HONOR_LEAD_MS,
  DOUBLE_HONOR_MULTIPLIER,
  DOUBLE_HONOR_WEEKDAYS,
  doubleHonorActive,
  honorEventMultiplier,
  weekdayOfDayKey,
} from './honor_event';
// warfare_quartermaster.ts is DELIBERATELY not re-exported here. It needs
// createNpc from '../entity' at runtime, and entity.ts imports this barrel for
// pvpFractionsFromRatings, so re-exporting it would close a value-level ESM
// cycle (entity -> pvp/index -> warfare_quartermaster -> entity). That happens
// to work today only because createNpc is called function-scoped; the day
// anything in the directory reaches for it at module scope it breaks at import
// time with an unhelpful error. Every other pvp import was type-only, so this
// is the one module that would make a leaf directory cycle-fragile.
//
// Its single consumer is the Sim coordinator during world init, so it is not
// public API in any meaningful sense: import it by path.
export { loadHonorState, savedHonorState } from './honor_persist';
export {
  countsWarfareRating,
  PVP_DEFENSE_CAP,
  PVP_OFFENSE_CAP,
  PVP_RATING_PER_PCT,
  PVP_VITALITY_CAP,
  PVP_VITALITY_RATING_PER_PCT,
  type PvpCaps,
  pvpDamageMultiplier,
  pvpFractionsFromRatings,
  pvpVitalityFromRating,
} from './power';
export {
  notePvpResurrectAtDeath,
  PVP_RESURRECT_WINDOW_SECONDS,
  type PvpResurrectDeath,
  pvpResurrectBarred,
  pvpResurrectEarned,
} from './pvp_resurrect';
export { pvpVitalityAppliesTo, updatePvpVitality } from './vitality';
export {
  isWorldPvpFlagged,
  isWorldPvpHostile,
  loadWorldPvpState,
  newWorldPvpBooks,
  savedWorldPvpFields,
  savedWorldPvpState,
  setWorldPvpFlag,
  toggleWorldPvpFlag,
  updateWorldPvp,
  WORLD_PVP_DISARM_MINUTES,
  type WorldPvpBooks,
  type WorldPvpMetaState,
  type WorldPvpSavedState,
  worldPvpDefeatLine,
  worldPvpDisarmRemaining,
  worldPvpInfoFor,
  worldPvpKillLine,
  worldPvpOnOwnedPetDamaged,
  worldPvpOnPlayerAided,
  worldPvpOnPlayerDamaged,
  worldPvpOnPlayerDeath,
  worldPvpPairRepeats,
} from './world_pvp';
export {
  WORLD_PVP_ASSIST_WINDOW,
  WORLD_PVP_DISARM_SECONDS,
  WORLD_PVP_DR_WINDOW_SECONDS,
  WORLD_PVP_GREY_LEVEL_GAP,
  WORLD_PVP_KILL_HONOR,
  WORLD_PVP_MIN_LEVEL,
  WORLD_PVP_STAKE_CAP_COPPER,
  WORLD_PVP_STAKE_FRACTION,
  type WorldPvpZonePolicy,
  worldPvpHitMarksAttacker,
  worldPvpPairExempt,
  worldPvpPairHostile,
  worldPvpPairMultiplier,
  worldPvpSplit,
  worldPvpStake,
  worldPvpVictimIsGrey,
} from './world_pvp_rules';
export { worldPvpFfaZones, worldPvpZonePolicyAt, worldPvpZonePolicyOf } from './world_pvp_zones';
