// Warfare Season 2 ("Vanguard"): the top tier of honor gear, sold beside the
// Warfare entry tier (content/pvp_honor.ts) by both honor quartermasters. One
// five-piece set per spec (27 sets, the raid sets' slots and 2/4 thresholds)
// plus weapons and jewelry. Built once from docs/design/warfare-season-2.md (names) and
// the named rules below by a one-off script, and maintained by hand from here:
// tests/warfare_season2.test.ts pins every rule, so an edit that breaks one
// fails there. The design doc is the review record.
//
// Every piece reads item level 35 (SEASON2_SOURCE_LEVEL 29 + the epic bump 6),
// level with the Ignivar raid tier, and keeps the honor discount so honor gear
// is never the raid pick in PvE (docs/design/warfare-season-2.md, "The PvE
// promise"):
//   - the stat line is SEASON2_STAT_FRACTION of the item-level-35 budget, with
//     stamina lifted to the FULL budget's stamina floor (the entry tier's rule):
//     a physical piece carries floor stamina and the rest of the line as
//     Strength or Agility, a caster piece the whole line as Intellect and
//     Spirit with floor stamina on top;
//   - ONE combat rating per piece, at SEASON2_COMBAT_RATING_SHARE of the
//     same-slot raid piece's rating total, in the main rating of the spec's
//     raid set; the rings carry the PvP hit cap instead;
//   - Spell Power (damage casters) or Healing Power (healers), so the full kit
//     carries the raid lane;
//   - armor is SEASON2_ARMOR_FRACTION of the mean armor of same-slot,
//     same-armor-type item-level-35 raid set pieces;
//   - Warfare Offense and Defense Rating equal the full slot budget, as on the
//     entry tier, so the existing caps bound every total.
// Sets are class-locked (requiredClass); their bonuses live in
// content/vanguard_item_sets.ts (text) and content/vanguard_set_bonuses.ts
// (engine rows). Pinned by tests/warfare_season2.test.ts.

import type { ItemDef } from '../types';

export const SEASON2_SOURCE_LEVEL = 29;
export const SEASON2_STAT_FRACTION = 0.9;
export const SEASON2_ARMOR_FRACTION = 0.9;
/** Warfare ratings per piece, as multiples of the slot budget (the entry tier
 *  carries 1x). Season 2 bonuses change abilities rather than add rating, so the
 *  pieces carry it instead. Tuned so the caps land on the FULL kit (the five
 *  pieces and a Season 2 weapon, plus entry-tier waist, feet and jewelry): with
 *  a one-hand weapon it reaches exactly the 30 percent Offense cap and the +80
 *  percent Vitality cap, and a two-hander sits one ring's worth over. A part kit
 *  stays below them, so a Warfare piece keeps beating a PvE piece in every slot
 *  (owner rebalance, 2026-10-02: at 2.2 and 3.4, three pieces plus Fury's two
 *  greatswords already reached both caps). A full Season 1 kit stops at +50
 *  percent Vitality. None of it applies in dungeons or raids. */
export const SEASON2_OFFENSE_RATING_MULT = 1.8;
export const SEASON2_DEFENSE_RATING_MULT = 2.9;
/** Combat ratings (owner request, 2026-10-02: "hit/haste/crit/spell power/healing
 *  power across all the gear", stamina still the priority). Every item-level-35
 *  raid set piece carries 85 rating (60 main plus 25 second), every raid weapon
 *  100 and every raid neck 25; a Season 2 piece carries a third, rounded down,
 *  as ONE rating: the main rating of its spec's raid set on armor (crit or
 *  haste), crit on the weapons and necks (haste on the healer neck). WoW's PvP
 *  pieces carried half (at item level 264 the Wrathful Gladiator belts carry 72
 *  offensive rating against the 144 on the raid belts), but resilience also cut
 *  the chance and size of a crit taken, which cancelled much of it; Warfare
 *  Defense is flat damage reduction and already capped on a full kit, so a
 *  third keeps the fight-length change near what WoW players actually felt.
 *  Stamina, the stat line and Warfare rating are untouched. */
export const SEASON2_COMBAT_RATING_SHARE = 1 / 3;
export const SEASON2_ARMOR_COMBAT_RATING = 28;
export const SEASON2_WEAPON_COMBAT_RATING = 33;
export const SEASON2_NECK_COMBAT_RATING = 8;
/** The rings carry Hit sized to the PvP cap instead: two melee rings remove the
 *  base 5 percent melee miss against a same-level player and two caster rings
 *  the 4 percent spell resist (types.ts meleeMissChance and spellHitChance, 10
 *  Hit Rating per percent). Dual-wield auto-attacks keep their extra 10 percent
 *  (combat/auto_attack.ts DUAL_WIELD_WHITE_MISS_PENALTY), as in classic, so the
 *  cap covers special attacks and single-weapon swings. Hit past the cap does nothing in PvP, so the rings stop
 *  there (the Cataclysm Gladiator's Ring of Accuracy). Heals are never resisted,
 *  so the healer ring swaps its Hit for the same amount of Haste (the Band of
 *  Meditation). No other Season 2 piece carries Hit. */
export const SEASON2_MELEE_RING_HIT_RATING = 25;
export const SEASON2_CASTER_RING_HIT_RATING = 20;
export const SEASON2_HEALER_RING_HASTE_RATING = 20;
/** Spell Power and Healing Power: the full Season 2 kit (the five pieces, the
 *  staff, the Season 2 neck and two rings, plus entry-tier waist and feet) lands
 *  on the raid caster and healer lanes, 86 and 172 (item_budget.ts
 *  casterLaneSpTotal and healerLaneHpTotal at item level 35); the PvP caster belt
 *  in WoW kept full spell power. The neck and rings copy the raid jewelry (4
 *  Spell Power, 8 Healing Power). The entry-tier waist and feet stay as they
 *  are, so their raid share (4 + 4 Spell Power, 8 + 8 Healing Power) rides on
 *  the five armor pieces: the raid piece's amount times 40/32 (Spell Power) or
 *  80/64 (Healing Power), rounded to whole points with the remainder on the
 *  helm and legs. The one staff serves both roles: the raid damage staff's 34
 *  Spell Power, and Healing Power up to the raid healer staff's 68 healing. */
export const SEASON2_JEWELRY_PRICES: Readonly<Record<'neck' | 'ring', number>> = {
  // 1.5 times the entry tier's old honor prices (neck 400, ring 275), the
  // armor's multiplier, with the ring rounded to the 25 the other prices sit on.
  neck: 600,
  ring: 425,
};
export const SEASON2_ARMOR_SLOTS = ['helmet', 'shoulder', 'chest', 'legs', 'gloves'] as const;
export const SEASON2_PRICES: Readonly<Record<string, number>> = {
  helmet: 1350,
  shoulder: 1050,
  chest: 1800,
  legs: 1575,
  gloves: 825,
};
export const SEASON2_WEAPON_PRICE = 1800;

/** One Season 2 set per spec, in class then spec order (the shop reads this). */
export interface Season2Set {
  setId: string;
  cls: string;
  spec: string;
  armorType: 'cloth' | 'leather' | 'mail';
  itemIds: readonly string[];
}

export const SEASON2_SETS: readonly Season2Set[] = [
  {
    setId: 'vanguard_warrior_arms',
    cls: 'warrior',
    spec: 'arms',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_arms_helmet',
      'vanguard_warrior_arms_shoulder',
      'vanguard_warrior_arms_chest',
      'vanguard_warrior_arms_legs',
      'vanguard_warrior_arms_gloves',
    ],
  },
  {
    setId: 'vanguard_warrior_fury',
    cls: 'warrior',
    spec: 'fury',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_fury_helmet',
      'vanguard_warrior_fury_shoulder',
      'vanguard_warrior_fury_chest',
      'vanguard_warrior_fury_legs',
      'vanguard_warrior_fury_gloves',
    ],
  },
  {
    setId: 'vanguard_warrior_prot',
    cls: 'warrior',
    spec: 'prot',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_prot_helmet',
      'vanguard_warrior_prot_shoulder',
      'vanguard_warrior_prot_chest',
      'vanguard_warrior_prot_legs',
      'vanguard_warrior_prot_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_holy',
    cls: 'paladin',
    spec: 'holy',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_holy_helmet',
      'vanguard_paladin_holy_shoulder',
      'vanguard_paladin_holy_chest',
      'vanguard_paladin_holy_legs',
      'vanguard_paladin_holy_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_protection',
    cls: 'paladin',
    spec: 'protection',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_protection_helmet',
      'vanguard_paladin_protection_shoulder',
      'vanguard_paladin_protection_chest',
      'vanguard_paladin_protection_legs',
      'vanguard_paladin_protection_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_retribution',
    cls: 'paladin',
    spec: 'retribution',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_retribution_helmet',
      'vanguard_paladin_retribution_shoulder',
      'vanguard_paladin_retribution_chest',
      'vanguard_paladin_retribution_legs',
      'vanguard_paladin_retribution_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_beast_mastery',
    cls: 'hunter',
    spec: 'beast_mastery',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_beast_mastery_helmet',
      'vanguard_hunter_beast_mastery_shoulder',
      'vanguard_hunter_beast_mastery_chest',
      'vanguard_hunter_beast_mastery_legs',
      'vanguard_hunter_beast_mastery_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_marksmanship',
    cls: 'hunter',
    spec: 'marksmanship',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_marksmanship_helmet',
      'vanguard_hunter_marksmanship_shoulder',
      'vanguard_hunter_marksmanship_chest',
      'vanguard_hunter_marksmanship_legs',
      'vanguard_hunter_marksmanship_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_survival',
    cls: 'hunter',
    spec: 'survival',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_survival_helmet',
      'vanguard_hunter_survival_shoulder',
      'vanguard_hunter_survival_chest',
      'vanguard_hunter_survival_legs',
      'vanguard_hunter_survival_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_assassination',
    cls: 'rogue',
    spec: 'assassination',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_assassination_helmet',
      'vanguard_rogue_assassination_shoulder',
      'vanguard_rogue_assassination_chest',
      'vanguard_rogue_assassination_legs',
      'vanguard_rogue_assassination_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_combat',
    cls: 'rogue',
    spec: 'combat',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_combat_helmet',
      'vanguard_rogue_combat_shoulder',
      'vanguard_rogue_combat_chest',
      'vanguard_rogue_combat_legs',
      'vanguard_rogue_combat_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_subtlety',
    cls: 'rogue',
    spec: 'subtlety',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_subtlety_helmet',
      'vanguard_rogue_subtlety_shoulder',
      'vanguard_rogue_subtlety_chest',
      'vanguard_rogue_subtlety_legs',
      'vanguard_rogue_subtlety_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_discipline',
    cls: 'priest',
    spec: 'discipline',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_discipline_helmet',
      'vanguard_priest_discipline_shoulder',
      'vanguard_priest_discipline_chest',
      'vanguard_priest_discipline_legs',
      'vanguard_priest_discipline_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_holy',
    cls: 'priest',
    spec: 'holy',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_holy_helmet',
      'vanguard_priest_holy_shoulder',
      'vanguard_priest_holy_chest',
      'vanguard_priest_holy_legs',
      'vanguard_priest_holy_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_shadow',
    cls: 'priest',
    spec: 'shadow',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_shadow_helmet',
      'vanguard_priest_shadow_shoulder',
      'vanguard_priest_shadow_chest',
      'vanguard_priest_shadow_legs',
      'vanguard_priest_shadow_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_elemental',
    cls: 'shaman',
    spec: 'elemental',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_elemental_helmet',
      'vanguard_shaman_elemental_shoulder',
      'vanguard_shaman_elemental_chest',
      'vanguard_shaman_elemental_legs',
      'vanguard_shaman_elemental_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_enhancement',
    cls: 'shaman',
    spec: 'enhancement',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_enhancement_helmet',
      'vanguard_shaman_enhancement_shoulder',
      'vanguard_shaman_enhancement_chest',
      'vanguard_shaman_enhancement_legs',
      'vanguard_shaman_enhancement_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_restoration',
    cls: 'shaman',
    spec: 'restoration',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_restoration_helmet',
      'vanguard_shaman_restoration_shoulder',
      'vanguard_shaman_restoration_chest',
      'vanguard_shaman_restoration_legs',
      'vanguard_shaman_restoration_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_arcane',
    cls: 'mage',
    spec: 'arcane',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_arcane_helmet',
      'vanguard_mage_arcane_shoulder',
      'vanguard_mage_arcane_chest',
      'vanguard_mage_arcane_legs',
      'vanguard_mage_arcane_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_fire',
    cls: 'mage',
    spec: 'fire',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_fire_helmet',
      'vanguard_mage_fire_shoulder',
      'vanguard_mage_fire_chest',
      'vanguard_mage_fire_legs',
      'vanguard_mage_fire_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_frost',
    cls: 'mage',
    spec: 'frost',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_frost_helmet',
      'vanguard_mage_frost_shoulder',
      'vanguard_mage_frost_chest',
      'vanguard_mage_frost_legs',
      'vanguard_mage_frost_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_affliction',
    cls: 'warlock',
    spec: 'affliction',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_affliction_helmet',
      'vanguard_warlock_affliction_shoulder',
      'vanguard_warlock_affliction_chest',
      'vanguard_warlock_affliction_legs',
      'vanguard_warlock_affliction_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_demonology',
    cls: 'warlock',
    spec: 'demonology',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_demonology_helmet',
      'vanguard_warlock_demonology_shoulder',
      'vanguard_warlock_demonology_chest',
      'vanguard_warlock_demonology_legs',
      'vanguard_warlock_demonology_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_destruction',
    cls: 'warlock',
    spec: 'destruction',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_destruction_helmet',
      'vanguard_warlock_destruction_shoulder',
      'vanguard_warlock_destruction_chest',
      'vanguard_warlock_destruction_legs',
      'vanguard_warlock_destruction_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_balance',
    cls: 'druid',
    spec: 'balance',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_balance_helmet',
      'vanguard_druid_balance_shoulder',
      'vanguard_druid_balance_chest',
      'vanguard_druid_balance_legs',
      'vanguard_druid_balance_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_feral',
    cls: 'druid',
    spec: 'feral',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_feral_helmet',
      'vanguard_druid_feral_shoulder',
      'vanguard_druid_feral_chest',
      'vanguard_druid_feral_legs',
      'vanguard_druid_feral_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_restoration',
    cls: 'druid',
    spec: 'restoration',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_restoration_helmet',
      'vanguard_druid_restoration_shoulder',
      'vanguard_druid_restoration_chest',
      'vanguard_druid_restoration_legs',
      'vanguard_druid_restoration_gloves',
    ],
  },
];

export const SEASON2_WEAPON_IDS: readonly string[] = [
  'vanguard_verdict_greatsword',
  'vanguard_oath_blade',
  'vanguard_fang_dagger',
  'vanguard_warstaff',
  'vanguard_feral_staff',
];

/** The Season 2 jewelry: one ring and one neck per role (Strength, Agility,
 *  damage caster, healer). Rings are not unique-equipped, so a player wears two
 *  of the same ring. */
export const SEASON2_JEWELRY_IDS: readonly string[] = [
  'vanguard_band_of_might',
  'vanguard_band_of_precision',
  'vanguard_band_of_focus',
  'vanguard_band_of_mending',
  'vanguard_pendant_of_might',
  'vanguard_pendant_of_precision',
  'vanguard_pendant_of_focus',
  'vanguard_pendant_of_mending',
];

export const SEASON2_ITEMS: Record<string, ItemDef> = {
  vanguard_warrior_arms_helmet: {
    id: 'vanguard_warrior_arms_helmet',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Greathelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_shoulder: {
    id: 'vanguard_warrior_arms_shoulder',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_chest: {
    id: 'vanguard_warrior_arms_chest',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_legs: {
    id: 'vanguard_warrior_arms_legs',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Legplates',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_gloves: {
    id: 'vanguard_warrior_arms_gloves',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Crushers',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_helmet: {
    id: 'vanguard_warrior_fury_helmet',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Visage',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_shoulder: {
    id: 'vanguard_warrior_fury_shoulder',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Shoulderguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_chest: {
    id: 'vanguard_warrior_fury_chest',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Chainmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    hasteRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_legs: {
    id: 'vanguard_warrior_fury_legs',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Leggings',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_gloves: {
    id: 'vanguard_warrior_fury_gloves',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Grips',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_helmet: {
    id: 'vanguard_warrior_prot_helmet',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_shoulder: {
    id: 'vanguard_warrior_prot_shoulder',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_chest: {
    id: 'vanguard_warrior_prot_chest',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Chestguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_legs: {
    id: 'vanguard_warrior_prot_legs',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_gloves: {
    id: 'vanguard_warrior_prot_gloves',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Handguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_paladin_holy_helmet: {
    id: 'vanguard_paladin_holy_helmet',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Circlet',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 11, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_shoulder: {
    id: 'vanguard_paladin_holy_shoulder',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 10, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_chest: {
    id: 'vanguard_paladin_holy_chest',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 14, sta: 8, spi: 9 },
    hasteRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_legs: {
    id: 'vanguard_paladin_holy_legs',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 12, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_gloves: {
    id: 'vanguard_paladin_holy_gloves',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Gloves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 9, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_helmet: {
    id: 'vanguard_paladin_protection_helmet',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_shoulder: {
    id: 'vanguard_paladin_protection_shoulder',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_chest: {
    id: 'vanguard_paladin_protection_chest',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_legs: {
    id: 'vanguard_paladin_protection_legs',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Legplates',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_gloves: {
    id: 'vanguard_paladin_protection_gloves',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_helmet: {
    id: 'vanguard_paladin_retribution_helmet',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_shoulder: {
    id: 'vanguard_paladin_retribution_shoulder',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_chest: {
    id: 'vanguard_paladin_retribution_chest',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Cuirass',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_legs: {
    id: 'vanguard_paladin_retribution_legs',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_gloves: {
    id: 'vanguard_paladin_retribution_gloves',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_helmet: {
    id: 'vanguard_hunter_beast_mastery_helmet',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_shoulder: {
    id: 'vanguard_hunter_beast_mastery_shoulder',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_chest: {
    id: 'vanguard_hunter_beast_mastery_chest',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_legs: {
    id: 'vanguard_hunter_beast_mastery_legs',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_gloves: {
    id: 'vanguard_hunter_beast_mastery_gloves',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_helmet: {
    id: 'vanguard_hunter_marksmanship_helmet',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_shoulder: {
    id: 'vanguard_hunter_marksmanship_shoulder',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_chest: {
    id: 'vanguard_hunter_marksmanship_chest',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_legs: {
    id: 'vanguard_hunter_marksmanship_legs',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_gloves: {
    id: 'vanguard_hunter_marksmanship_gloves',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_helmet: {
    id: 'vanguard_hunter_survival_helmet',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_shoulder: {
    id: 'vanguard_hunter_survival_shoulder',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_chest: {
    id: 'vanguard_hunter_survival_chest',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    hasteRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_legs: {
    id: 'vanguard_hunter_survival_legs',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_gloves: {
    id: 'vanguard_hunter_survival_gloves',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_rogue_assassination_helmet: {
    id: 'vanguard_rogue_assassination_helmet',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_shoulder: {
    id: 'vanguard_rogue_assassination_shoulder',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_chest: {
    id: 'vanguard_rogue_assassination_chest',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_legs: {
    id: 'vanguard_rogue_assassination_legs',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_gloves: {
    id: 'vanguard_rogue_assassination_gloves',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_helmet: {
    id: 'vanguard_rogue_combat_helmet',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_shoulder: {
    id: 'vanguard_rogue_combat_shoulder',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_chest: {
    id: 'vanguard_rogue_combat_chest',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    hasteRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_legs: {
    id: 'vanguard_rogue_combat_legs',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_gloves: {
    id: 'vanguard_rogue_combat_gloves',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_helmet: {
    id: 'vanguard_rogue_subtlety_helmet',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_shoulder: {
    id: 'vanguard_rogue_subtlety_shoulder',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_chest: {
    id: 'vanguard_rogue_subtlety_chest',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_legs: {
    id: 'vanguard_rogue_subtlety_legs',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_gloves: {
    id: 'vanguard_rogue_subtlety_gloves',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_priest_discipline_helmet: {
    id: 'vanguard_priest_discipline_helmet',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_shoulder: {
    id: 'vanguard_priest_discipline_shoulder',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_chest: {
    id: 'vanguard_priest_discipline_chest',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    hasteRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_legs: {
    id: 'vanguard_priest_discipline_legs',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_gloves: {
    id: 'vanguard_priest_discipline_gloves',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_helmet: {
    id: 'vanguard_priest_holy_helmet',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    critRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_shoulder: {
    id: 'vanguard_priest_holy_shoulder',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    critRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_chest: {
    id: 'vanguard_priest_holy_chest',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    critRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_legs: {
    id: 'vanguard_priest_holy_legs',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    critRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_gloves: {
    id: 'vanguard_priest_holy_gloves',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    critRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_helmet: {
    id: 'vanguard_priest_shadow_helmet',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_shoulder: {
    id: 'vanguard_priest_shadow_shoulder',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_chest: {
    id: 'vanguard_priest_shadow_chest',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_legs: {
    id: 'vanguard_priest_shadow_legs',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_gloves: {
    id: 'vanguard_priest_shadow_gloves',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_shaman_elemental_helmet: {
    id: 'vanguard_shaman_elemental_helmet',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Coif',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_shoulder: {
    id: 'vanguard_shaman_elemental_shoulder',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_chest: {
    id: 'vanguard_shaman_elemental_chest',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_legs: {
    id: 'vanguard_shaman_elemental_legs',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_gloves: {
    id: 'vanguard_shaman_elemental_gloves',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_helmet: {
    id: 'vanguard_shaman_enhancement_helmet',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, agi: 12, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_shoulder: {
    id: 'vanguard_shaman_enhancement_shoulder',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, agi: 10, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_chest: {
    id: 'vanguard_shaman_enhancement_chest',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Chainmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, agi: 15, sta: 8 },
    hasteRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_legs: {
    id: 'vanguard_shaman_enhancement_legs',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, agi: 13, sta: 7 },
    hasteRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_gloves: {
    id: 'vanguard_shaman_enhancement_gloves',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Grips',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, agi: 9, sta: 6 },
    hasteRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_helmet: {
    id: 'vanguard_shaman_restoration_helmet',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Circlet',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 11, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_shoulder: {
    id: 'vanguard_shaman_restoration_shoulder',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 10, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_chest: {
    id: 'vanguard_shaman_restoration_chest',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 14, sta: 8, spi: 9 },
    hasteRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_legs: {
    id: 'vanguard_shaman_restoration_legs',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Kilt',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 12, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_gloves: {
    id: 'vanguard_shaman_restoration_gloves',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Handwraps',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 9, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_mage_arcane_helmet: {
    id: 'vanguard_mage_arcane_helmet',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Hood",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_shoulder: {
    id: 'vanguard_mage_arcane_shoulder',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Amice",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_chest: {
    id: 'vanguard_mage_arcane_chest',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Robe",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    hasteRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_legs: {
    id: 'vanguard_mage_arcane_legs',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Trousers",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_gloves: {
    id: 'vanguard_mage_arcane_gloves',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Gloves",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_helmet: {
    id: 'vanguard_mage_fire_helmet',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_shoulder: {
    id: 'vanguard_mage_fire_shoulder',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_chest: {
    id: 'vanguard_mage_fire_chest',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Robes',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_legs: {
    id: 'vanguard_mage_fire_legs',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_gloves: {
    id: 'vanguard_mage_fire_gloves',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Gloves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_helmet: {
    id: 'vanguard_mage_frost_helmet',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    hasteRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_shoulder: {
    id: 'vanguard_mage_frost_shoulder',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Shoulderpads',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    hasteRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_chest: {
    id: 'vanguard_mage_frost_chest',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Vestment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    hasteRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_legs: {
    id: 'vanguard_mage_frost_legs',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    hasteRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_gloves: {
    id: 'vanguard_mage_frost_gloves',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Mitts',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    hasteRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_warlock_affliction_helmet: {
    id: 'vanguard_warlock_affliction_helmet',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    hasteRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_shoulder: {
    id: 'vanguard_warlock_affliction_shoulder',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    hasteRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_chest: {
    id: 'vanguard_warlock_affliction_chest',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    hasteRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_legs: {
    id: 'vanguard_warlock_affliction_legs',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    hasteRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_gloves: {
    id: 'vanguard_warlock_affliction_gloves',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    hasteRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_helmet: {
    id: 'vanguard_warlock_demonology_helmet',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_shoulder: {
    id: 'vanguard_warlock_demonology_shoulder',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Spaulders',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_chest: {
    id: 'vanguard_warlock_demonology_chest',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_legs: {
    id: 'vanguard_warlock_demonology_legs',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_gloves: {
    id: 'vanguard_warlock_demonology_gloves',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Grips',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_helmet: {
    id: 'vanguard_warlock_destruction_helmet',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_shoulder: {
    id: 'vanguard_warlock_destruction_shoulder',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_chest: {
    id: 'vanguard_warlock_destruction_chest',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Robes',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_legs: {
    id: 'vanguard_warlock_destruction_legs',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_gloves: {
    id: 'vanguard_warlock_destruction_gloves',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Gloves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_druid_balance_helmet: {
    id: 'vanguard_druid_balance_helmet',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Headdress',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, int: 14, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_shoulder: {
    id: 'vanguard_druid_balance_shoulder',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, int: 12, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_chest: {
    id: 'vanguard_druid_balance_chest',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Vest',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, int: 17, sta: 8, spi: 6 },
    critRating: 28,
    spellPower: 10,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_legs: {
    id: 'vanguard_druid_balance_legs',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, int: 15, sta: 7, spi: 5 },
    critRating: 28,
    spellPower: 9,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_gloves: {
    id: 'vanguard_druid_balance_gloves',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, int: 11, sta: 6, spi: 4 },
    critRating: 28,
    spellPower: 6,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_helmet: {
    id: 'vanguard_druid_feral_helmet',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Helm',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, str: 12, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_shoulder: {
    id: 'vanguard_druid_feral_shoulder',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, str: 10, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_chest: {
    id: 'vanguard_druid_feral_chest',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, str: 15, sta: 8 },
    critRating: 28,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_legs: {
    id: 'vanguard_druid_feral_legs',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, str: 13, sta: 7 },
    critRating: 28,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_gloves: {
    id: 'vanguard_druid_feral_gloves',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, str: 9, sta: 6 },
    critRating: 28,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_helmet: {
    id: 'vanguard_druid_restoration_helmet',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Crown',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, int: 11, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 38,
    pvpDefenseRating: 61,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_shoulder: {
    id: 'vanguard_druid_restoration_shoulder',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Mantle',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, int: 10, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 32,
    pvpDefenseRating: 52,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_chest: {
    id: 'vanguard_druid_restoration_chest',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Vest',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, int: 14, sta: 8, spi: 9 },
    hasteRating: 28,
    healPower: 20,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_legs: {
    id: 'vanguard_druid_restoration_legs',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, int: 12, sta: 7, spi: 8 },
    hasteRating: 28,
    healPower: 18,
    pvpOffenseRating: 40,
    pvpDefenseRating: 64,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_gloves: {
    id: 'vanguard_druid_restoration_gloves',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, int: 9, sta: 6, spi: 6 },
    hasteRating: 28,
    healPower: 12,
    pvpOffenseRating: 31,
    pvpDefenseRating: 49,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_verdict_greatsword: {
    id: 'vanguard_verdict_greatsword',
    name: "Vanguard's Verdict",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 54, max: 81, speed: 3.4 },
    stats: { str: 19, sta: 11 },
    critRating: 33,
    pvpOffenseRating: 59,
    pvpDefenseRating: 96,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  vanguard_oath_blade: {
    id: 'vanguard_oath_blade',
    name: "Vanguard's Oath",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 36, max: 54, speed: 2.6 },
    stats: { str: 15, sta: 8 },
    critRating: 33,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  vanguard_fang_dagger: {
    id: 'vanguard_fang_dagger',
    name: "Vanguard's Fang",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 25, max: 37, speed: 1.8, dagger: true },
    stats: { agi: 15, sta: 8 },
    critRating: 33,
    pvpOffenseRating: 45,
    pvpDefenseRating: 73,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  vanguard_warstaff: {
    id: 'vanguard_warstaff',
    name: "Vanguard's Warstaff",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 47, max: 71, speed: 3 },
    stats: { int: 23, sta: 11, spi: 7 },
    critRating: 33,
    spellPower: 34,
    healPower: 34,
    pvpOffenseRating: 59,
    pvpDefenseRating: 96,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  vanguard_feral_staff: {
    id: 'vanguard_feral_staff',
    name: "Vanguard's Feral Staff",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 47, max: 71, speed: 3 },
    stats: { str: 10, agi: 9, sta: 11 },
    critRating: 33,
    pvpOffenseRating: 59,
    pvpDefenseRating: 96,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },

  // Jewelry (owner request, 2026-10-02). The stat line follows the armor rule
  // (SEASON2_STAT_FRACTION of the item-level-35 ring or neck budget, stamina at
  // the full budget's floor), one below the raid ring's and two below the raid
  // neck's. Warfare rating is the entry-tier jewelry's (13 on a ring, 14 on a
  // neck), not a Season 2 multiple: the 1.8x and 2.9x multipliers were sized so
  // the full kit WITH entry-tier jewelry reaches the caps, and this jewelry
  // replaces that jewelry slot for slot, so every cap total is unchanged. No
  // class lock and no armor type: every class sees all eight.
  vanguard_band_of_might: {
    id: 'vanguard_band_of_might',
    name: "Vanguard's Band of Might",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 9, sta: 5 },
    hitRating: 25,
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 425,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_band_of_precision: {
    id: 'vanguard_band_of_precision',
    name: "Vanguard's Band of Precision",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 9, sta: 5 },
    hitRating: 25,
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 425,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_band_of_focus: {
    id: 'vanguard_band_of_focus',
    name: "Vanguard's Band of Focus",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 10, sta: 5, spi: 4 },
    hitRating: 20,
    spellPower: 4,
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 425,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_band_of_mending: {
    id: 'vanguard_band_of_mending',
    name: "Vanguard's Band of Mending",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 7, sta: 5, spi: 7 },
    hasteRating: 20,
    healPower: 8,
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 425,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_pendant_of_might: {
    id: 'vanguard_pendant_of_might',
    name: "Vanguard's Pendant of Might",
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 9, sta: 5 },
    critRating: 8,
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_pendant_of_precision: {
    id: 'vanguard_pendant_of_precision',
    name: "Vanguard's Pendant of Precision",
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 9, sta: 5 },
    critRating: 8,
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_pendant_of_focus: {
    id: 'vanguard_pendant_of_focus',
    name: "Vanguard's Pendant of Focus",
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 10, sta: 5, spi: 4 },
    critRating: 8,
    spellPower: 4,
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  vanguard_pendant_of_mending: {
    id: 'vanguard_pendant_of_mending',
    name: "Vanguard's Pendant of Mending",
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 7, sta: 5, spi: 7 },
    hasteRating: 8,
    healPower: 8,
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
};

export const SEASON2_STOCK: readonly string[] = Object.keys(SEASON2_ITEMS);
